### ISSUE TITLE
Only add new videos

### ISSUE THREAD

**Issue by orschiro** [RobbieClarken/youtube-channel-to-playlist#3]
Dear @RobbieClarken, 

Running into a different issue now. 

As mentioned on the other issue, the adding to a playlist works now. 

However, it slightly defeats the purpose. 

My end goal: create a playlist mix of three different channels with on-going videos starting from now. 

The command I performed yesterday started to add all (historic) videos from the channel to the playlist. Soon I hit the playlist limit (only X amount of videos) without even having gotten to "today". 

Do you have any suggestion for me?

Yours appreciatively

**Comment by RobbieClarken** [comment]
Hi @orschiro - I didn't even know there was a limit to how many videos can be in a playlist. Perhaps you could create seperate playlists for each year or month? My script won't segregate them automatically but it shouldn't be too much trouble for you to modify it to do this. You can see it is [sorting the videos by the date published on line 59](https://github.com/RobbieClarken/youtube-channel-to-playlist/blob/7dee36e9509f4d9fde0f663f905e092d70af4815/channel_to_playlist.py#L59) so you could add some filtering there. If you wanted to try this, you can clone the repo and install your local copy with:

```
git clone https://github.com/RobbieClarken/youtube-channel-to-playlist
pip3 install -U -e youtube-channel-to-playlist
```

**Comment by orschiro** [comment]
Thank you @RobbieClarken. How do you feel about a `--since` option? Would you find it useful to add to your script?

    channel_to_playlist --secrets client_secrets.json UCgxzjK6GuOHVKR_08TT4hJQ PLlgnub_DBR_CszAWpJypwst0OFDxW6jOJ --since 2018-09-30

**Comment by RobbieClarken** [comment]
I can see that being useful to other people so I'd be happy to include it if you want to submit a PR. I'd suggest both a `--before` and `--after` option.

**Comment by orschiro** [comment]
OK, let me see if I am able to implement that and send you a PR. :)

**Comment by RobbieClarken** [comment]
Hi @orschiro - I discovered a need for these options myself so went ahead and implemented them. They are documented in the readme.

**Comment by orschiro** [comment]
Nice, thanks Robbie!
